### ISSUE TITLE
Spawn / void belt not working if placed by blueprints

### ISSUE THREAD

**Issue by iceman121212** [MakuraYami/factorio-spawn-belt#4]
Would be very helpful for simulation purposes.

**Comment by MakuraYami** [comment]
I'll probably get back to factorio once 0.15 hits, haven't been playing recently. I'll work on this once that's out

**Comment by MakuraYami** [comment]
Just a status update. Patched the mod to 0.15 today but didn't get around to make this yet. I will soon

**Comment by MakuraYami** [comment]
I've pushed an update with this fix (1.0.5). In the future please head over to the new repository for suggestions and bug reports

https://github.com/MakuraYami/factorio-mods
