### ISSUE TITLE
Default to not filling the belt

### ISSUE THREAD

**Issue by tsuckow** [MakuraYami/factorio-spawn-belt#6]
If you place a chest with an item in it and then place the spawn belt it will output iron ore for a period of time before changing to the item in the chest. A safer default would be to output nothing until there is something it should output.

**Comment by MakuraYami** [comment]
It's possible to make it choose the chest item directly on placing it also, it checks for changes in chest / circuit network on a set interval. I think removing the default might be useful but I'm worried people will get confused when using the mod, thinking it does not work.

I will fix the issue you described, if the default should be removed is something still up for discussion.

**Comment by MakuraYami** [comment]
I've pushed an update (1.0.5) with this fix. For future reports and discussions please head over to the new repository (I've moved all my mods into one repo)

https://github.com/MakuraYami/factorio-mods
